import "@/styles/globals.css";
import Header from "@/components/header";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Providers from "./interaction/Provider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

// 新增布局 Props 类型
type RootLayoutProps = {
  children: React.ReactNode;
  params: {
    __next_route_groups?: string[];
  };
};

export default async function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
